# General
name: data science social
description: data projects, data thoughts
url: http://annemanguyen.github.io

markdown: kramdown
highlighter: rouge

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: 
mail: anne.ma.nguyen@gmail.com
github: annemanguyen
linkedin: in/annemanguyen 

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
